version: '2'
services:
  default:
    container_name: default
    # includes mono and dotnet sdk
    image: tomzo/dotnet-ide:2.1.0
    links:
      - nuget:nuget
    volumes:
      - ${IDE_IDENTITY}:/ide/identity:ro
      - ${IDE_WORK}:/ide/work
    env_file:
      - ${ENV_FILE}
  nuget:
    image: ${AIT_DOCKER_IMAGE_NAME}:${AIT_DOCKER_IMAGE_TAG}
    volumes:
      - ${IDE_WORK}/e2e/liget-compat/data/:/var/baget
      - ${IDE_WORK}/e2e/input:/data/simple #simulates LiGet's storage
    env_file:
      - ${ENV_FILE}
    mem_limit: 550m
